# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zachfedor
email: zachfedor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Perfection is achieved, not when there is nothing more to add,
  but when there is nothing left to take away.
  - Antoine de Saint-Exupery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zachfedor.github.io" # the base hostname & protocol for your site
twitter_username: zachfedor
github_username:  zachfedor

# Build settings
markdown: kramdown
